name: mangband # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.3' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Multi players version of Angband
description: |
   Mangband is a free multiplayer implementation of the roguelike game, Angband. Gameplay differs in a number of key ways from Angband: it is no longer turn based, characters do not die permanantly and a dungeon at certain depth is persistent as long as at least one player sits on this level ensuring that players can meet, fight together and rescue others.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mangband_icon.png
title: MAngband

apps:
  mangband:
    command: mangband
parts:
  mangband:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mangband: build/
      mangband.1: man/man1/

architectures:
  - build-on: amd64

